global:
 scrape_interval: 5s

alerting:
 alertmanagers:
  - static_configs:
    - targets:
      -  localhost:9093

rule_files:
 - "alert.rules.yml"

scrape_configs:
 - job_name: "prometheus"
   static_configs:
    - targets:
      - localhost:9090
 - job_name: "node"
   static_configs:
    - targets:
      - 10.14.40.5:9100
      - 10.14.40.7:9100
